version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: auction
  web:
    command: "npm start"
    image: anjoseph/auction:first
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root@db/auction